spring:
  datasource:
    url: jdbc:postgresql://localhost/metaconference_serverlist
    username: metaconference
    data-password: metaconference
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
